M48
; DRILL file {KiCad (7.0.0)} date Mon May 29 03:25:20 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-29T03:25:20+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.6575Y-2.7331
X4.6575Y-3.5331
X6.3575Y-2.7331
X6.3575Y-3.5331
T0
M30
